### ISSUE TITLE
Inline editing  in list view not working in v8.2

### ISSUE THREAD

**Issue by leadssolution** [salesagility/SuiteCRM-Core#411]
Inline editing in list view not working in v8.2
I know this issue has been posted many times, but I wanted an update on future plans.
Will this be supported in the future? It is vital for our business so I need to know so we can make thr transition to another CRM if needed.

Thanks.

**Comment by johnM2401** [comment]
Hey!

Thanks for getting in touch.

I'm afraid that the Inline Editing behaviour on Suite8 listviews is still under internal deliberation, so I don't have a concrete answer for you as of yet.


However, in the meantime, you could try changing your modules to use the Suite7-style compatibility mode, to see if this suits your needs?

It will present as so:
![image](https://github.com/salesagility/SuiteCRM-Core/assets/13675281/5a0cd090-d012-4346-9a54-8a35a401f8b4)

<br>

To make this change:

You can copy the file:
```config/services/module/module_routing.yaml```

Into the /extensions/ folder at:
```extensions/[create a folder here]/config/module_routing.yaml```

This module_routing.yaml file is filled with index/List/Record view routings for each module, ie:
```
    leads:
      index: true
      list: true
      record: true
    contacts:
      index: true
      list: true
      record: true
```
"true" means it uses the Suite8 view
"false" means it'll use the Legacy Suite7 view

So, for example, to change Accounts to use the Legacy Listview, you'd change the following in the 
```/extensions/xxxx/config/module_routing.yaml``` file:
 ```   
    accounts:
      index: true
      list: true
      record: true
```
to
```
    accounts:
      index: false
      list: false
      record: true
```
Then, in console/terminal, run ```./bin/console cache:clear``` in the root of the project to clear cache, and you should get the Suite7-style listview .
(You may also need to clear your browser cache)

<br>


Please get in touch if you have encountered any issues with Suite7/Suite8, or have further questions.
Thanks!
