### ISSUE TITLE
docker setup - database connection error

### ISSUE THREAD

**Issue by ROBJkE** [salesagility/SuiteCRM-Core#69]
#### Issue

I try to install suitecrm 8 with a docker setup.  
Here is my `docker-compose`

``` yml
version: '3.5'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - suitecrm_db_data:/var/lib/mysql
      - ./db/mariaconf/90-my.cnf:/etc/mysql/mariadb.conf.d/90-my.cnf

  app:
    depends_on:
      - mariadb
    build: .
    ports:
      - "8071:8080"
    environment:
      SUITECRM_DB_HOST: mariadb:3306
    volumes:
      - "./app:/var/www/html"
      - "./logs:/var/www/logs"
    links:
      - "mariadb:dbsuitecrm"

volumes:
  suitecrm_db_data: {}
```

Both containers are up and running.  
If i try to connect with the DB from my app container with DB Tool like Adminer it works like a charm. (with server alias `dbsuitecrm`)
If i do the suitecrm install routine it says `database connection error`. I use the same credentials as in Adminer. 

Also i setup a database on a remote machine and try to connect within the suitecrm install routine but it fails too.  
With Adminer i can access the remote DB.

#### Expected Behavior
Connect to database

#### Actual Behavior
Doesn't connect to database

#### Steps to Reproduce
setup docker-compose with either mariadb or mysql and try to install

#### Your Environment

* SuiteCRM Version used: 8.0.3 (production)
* Environment: Docker, Nginx / PHP8 / MariaDB

#### Conclusion
I am not super familiar with docker so maybe the fault is mine.  
If someone has a working docker setup for suitecrm 8 it would be nice if you could share it.

**Comment by johnM2401** [comment]
Hey there, 

<br>

Would you be able to share what you are entereing for the "Host Name" and "Database Port" when installing Suite8?

I'm not much of a docker expert, but I may be able to point in the right direction!

<br>

I believe Suite8 currently has issues when using localhost as the Hostname.
Perhaps that is the issue, if this is what you are using?


<br>

Also, have you tried using the same environment/steps/credentials when installing Suite7, to see if you are able to install Suite7 via the exact same method?

It may be worth doing so to rule out whether this is specifically an issue with Suite8, or a larger issue with the environment itself

Thanks!

**Comment by ROBJkE** [comment]
@johnM2401 thank you for your response. I updated my `docker-compose` and my `Dockerfile` a bit. So i share my latest version with you. I'm not much of a docker pro too so forgive possible errors.

``` yml
version: '3.5'

networks:
  suiteNetwork:
    driver: bridge

services:
  database:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - suitecrm_db_data:/var/lib/mysql
      - ./db/mariaconf/90-my.cnf:/etc/mysql/mariadb.conf.d/90-my.cnf
    networks:
      suiteNetwork:
        aliases:
          - suitecrmdb

  app:
    depends_on:
      - database
    build: .
    ports:
      - "8071:8080"
    environment:
      DATABASE_URL: mysql://master:xxxxxx@suitecrmdb/suitecrm_8
    volumes:
      - "./app:/var/www/html"
      - "./logs:/var/www/logs"
    links:
      - "database"
    networks:
      suiteNetwork:
        aliases:
          - suitecrm

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8072:8080"
    links:
      - "database"
    networks:
      suiteNetwork:
        aliases:
          - suitecrmadminer

volumes:
  suitecrm_db_data: {}
```

The corresponding Dockerfile:
``` Dockerfile
FROM alpine:3.14
LABEL Maintainer="Tim de Pater <code@trafex.nl>"
LABEL Description="Lightweight container with Nginx 1.20 & PHP 8.0 based on Alpine Linux."

ENV ALPINE_MIRROR "http://dl-cdn.alpinelinux.org/alpine"
RUN echo "${ALPINE_MIRROR}/v3.11/main/" >> /etc/apk/repositories

# Install packages and remove default server definition
RUN apk --no-cache add \
  curl \
  bash \
  shadow \
  tar \
  git \
  libgcc \
  libstdc++ \
  libuv \
  nginx \
  php8 \
  php8-cli \
  php8-ctype \
  php8-curl \
  php8-dom \
  php8-fileinfo \
  php8-fpm \
  php8-gd \
  php8-intl \
  php8-json \
  php8-mbstring \
  php8-mysqli \
  php8-opcache \
  php8-openssl \
  php8-pdo \
  php8-phar \
  php8-session \
  php8-simplexml \
  php8-tokenizer \
  php8-xml \
  php8-xmlreader \
  php8-xmlwriter \
  php8-zip \
  php8-zlib \
  supervisor \
  nodejs npm --repository="http://dl-cdn.alpinelinux.org/alpine/v3.14/main/" \
  && usermod -u 1000 nobody && groupmod -g 1000 nobody

# Create symlink so programs depending on `php` still function
RUN ln -s /usr/bin/php8 /usr/bin/php

# Configure nginx
COPY config/nginx.conf /etc/nginx/nginx.conf

# Configure PHP-FPM
COPY config/fpm-pool.conf /etc/php8/php-fpm.d/www.conf
COPY config/php.ini /etc/php8/conf.d/custom.ini

# Configure supervisord
COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Install composer from the official image
COPY --from=composer /usr/bin/composer /usr/bin/composer

# set homedir for nobody `shadow` package required
RUN mkdir /home/nobody
RUN chown -R nobody.nobody /home/nobody
RUN usermod -d /home/nobody nobody

# Setup document root
RUN mkdir -p /var/www/html

COPY --chown=nobody app/ /var/www/html/

# Make sure files/folders needed by the processes are accessable when they run under the nobody user
RUN chown -R nobody:nobody /var/www/html && \
  chown -R nobody:nobody /run && \
  chown -R nobody:nobody /var/lib/nginx && \
  chown -R nobody:nobody /var/log/nginx

# Switch to use a non-root user from here on
USER nobody

# add .bashrc
RUN touch /home/nobody/.bashrc

# Add application
WORKDIR /var/www/html

# composer install
#RUN composer install

# Expose the port nginx is reachable on
EXPOSE 8080

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# Configure a healthcheck to validate that everything is up&running
HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping
```

The credentials i used to install suite8:
- Hostname: suitecrmdb
- Port: 3306 and empty (tried both)

Install failed with following response from graphql API:
(screenshot follows)

So with the exactly same docker-compose, Dockerfile and credentials i installed suite7.12.5 successfully:
![image](https://user-images.githubusercontent.com/26817419/162627093-0e8b8ea3-5edc-4472-9f6a-eebc87a6a25f.png)

So my guess is that i miss some issues with symfony/doctrine/graphql in conjunction with a docker setup.
Because the general docker setup seems to work. I can connect to DB in the adminer container and i successfully installed Suite7
